CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
	id INTEGER(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    burger_name VARCHAR(200) NOT NULL,
    devoured BOOLEAN DEFAULT false NOT NULL,
    date TIMESTAMP NOT NULL
);